SELECT DISTINCT(A.CAR_ID) -- 코드 중복이 없어야 해서 DISTINCT 사용

FROM CAR_RENTAL_COMPANY_CAR AS A

INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
ON A.CAR_ID = B.CAR_ID

WHERE CAR_TYPE = '세단' AND MONTH(START_DATE) = 10

ORDER BY CAR_ID DESC